using System.Collections.Generic;
using UnityEngine;

public class DPSManager : MonoBehaviour
{
    public List<DPS> dpsTargets = new List<DPS>();

    private float startTime;
    private bool isMeasuring = false;

    void Start()
    {
        dpsTargets.AddRange(GetComponentsInChildren<DPS>());
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.F1))
        {
            if (!isMeasuring)
            {
                StartMeasuring();
            }
            else
            {
                StopAndReport();
            }
        }
    }

    public void StartMeasuring()
    {
        startTime = Time.time;
        isMeasuring = true;

        foreach (var dps in dpsTargets)
        {
            dps.ResetDamage();
        }

        Debug.Log("ğŸ“Š DPS ì¸¡ì • ì‹œì‘!");
    }

    public void StopAndReport()
    {
        isMeasuring = false;

        float totalTime = Time.time - startTime;
        float totalDamage = 0f;

        foreach (var dpss in dpsTargets)
        {
            Debug.Log($"[{dpss.name}] ëˆ„ì  ë°ë¯¸ì§€: {dpss.TotalDamage:F1}");
            totalDamage += dpss.TotalDamage;
        }

        float dps = totalTime > 0f ? totalDamage / totalTime : 0f;

        Debug.Log($"ğŸ§  ì „ì²´ DPS: {dps:F2} (ì´ í”¼í•´: {totalDamage:F1} / ì‹œê°„: {totalTime:F2}ì´ˆ)");
    }
}
